# Generated by Django 3.2.3 on 2021-06-15 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_actnowuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="actnowuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actnowuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
