# Generated by Django 3.2.3 on 2021-06-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_actnowapplication"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actnowapplication",
            options={"verbose_name": "Application"},
        ),
        migrations.AddField(
            model_name="actnowuser",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as deleted.",
                verbose_name="deleted",
            ),
        ),
        migrations.AlterField(
            model_name="actnowuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. ",
                verbose_name="active",
            ),
        ),
    ]
