# Generated by Django 3.2.3 on 2021-07-09 10:33

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_is_deleted_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actnowuser",
            name="username",
            field=models.CharField(
                blank=True,
                default="",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
            preserve_default=False,
        ),
    ]
