[build-system]
requires = [
    "setuptools >= 56.0.0",
    "wheel >= 0.36.0",
    "setuptools_scm[toml]>=6.0.0",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.setuptools_scm]
write_to = "VERSION.txt"
