# Generated by Django 3.2.3 on 2021-06-16 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Petition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="details of petition"),
                ),
                (
                    "recipients",
                    models.CharField(max_length=255, verbose_name="recipients"),
                ),
                (
                    "problem_to_address",
                    models.TextField(verbose_name="problem to be addressed"),
                ),
                (
                    "number_of_signature_required",
                    models.IntegerField(verbose_name="number of signature required"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="", verbose_name="image"),
                ),
                (
                    "video",
                    models.FileField(blank=True, upload_to="", verbose_name="vide"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PetitionSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, verbose_name="comment")),
                (
                    "petition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="petitions.petition",
                    ),
                ),
                (
                    "signator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user who signed the petition",
                    ),
                ),
            ],
            options={
                "unique_together": {("petition", "signator")},
            },
        ),
    ]
