# Generated by Django 3.2.3 on 2021-06-18 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(max_length=1024, verbose_name='details of petition')),
                ('recipients', models.CharField(max_length=255, verbose_name='recipients')),
                ('problem_statement', models.TextField(max_length=1024, verbose_name='problem statement')),
                ('number_of_signatures_required', models.PositiveIntegerField(default=0, verbose_name='number of signatures required')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='image')),
                ('video', models.FileField(blank=True, upload_to='', verbose_name='video')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='comment')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='petitions.petition', verbose_name='petition')),
                ('signatory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='signatory')),
            ],
            options={
                'unique_together': {('petition', 'signatory')},
            },
        ),
    ]
