# Generated by Django 3.2.3 on 2021-07-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petitions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="anonymous",
            field=models.BooleanField(default=False, verbose_name="anonymous"),
        ),
    ]
