# Generated by Django 3.2.3 on 2021-06-17 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="petition",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="signature",
            name="petition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signatures",
                to="petitions.petition",
                verbose_name="petition",
            ),
        ),
        migrations.AlterField(
            model_name="signature",
            name="signatory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="signatory",
            ),
        ),
    ]
