# Generated by Django 3.2.3 on 2021-07-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0002_signature_sign_anonymously"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("link", models.URLField(verbose_name="link", unique=True)),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="petition",
            name="source",
            field=models.ManyToManyField(blank=True, to="petitions.Source"),
        ),
    ]
