# Generated by Django 3.2.3 on 2021-07-12 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petitions", "0002_add_source_to_pettition"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="followers",
            field=models.ManyToManyField(
                related_name="petitions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="followers",
            ),
        ),
    ]
