# Generated by Django 3.2.5 on 2021-08-09 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_profile_data"),
        ("petitions", "0003_petition_followers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="followers",
            field=models.ManyToManyField(
                related_name="petitions",
                to="profiles.Profile",
                verbose_name="followers",
            ),
        ),
        migrations.AlterField(
            model_name="petition",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profile",
                verbose_name="owner",
            ),
        ),
        migrations.AlterField(
            model_name="signature",
            name="signatory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.profile",
                verbose_name="signatory",
            ),
        ),
    ]
