# Generated by Django 3.2.3 on 2021-06-10 04:07

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models

import actnow.profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="About me"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        max_length=30, upload_to="", blank=True, null=True
                    ),
                ),
                ("location", models.TextField()),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "social_media_link",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[
                            actnow.profiles.validators.validate_social_media_link
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
