# Generated by Django 3.2.3 on 2021-06-10 16:55

import django.db.models.deletion
from django.db import migrations, models

import actnow.profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("website_link", models.URLField(blank=True, null=True)),
                (
                    "social_media_link",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[
                            actnow.profiles.validators.validate_social_media_link
                        ],
                    ),
                ),
                (
                    "person_1",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_1",
                        to="profiles.userprofile",
                    ),
                ),
                (
                    "person_2",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_2",
                        to="profiles.userprofile",
                    ),
                ),
            ],
        ),
    ]
