# Generated by Django 3.2.3 on 2021-06-14 06:57

from django.db import migrations, models

import actnow.profiles.validators


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.TextField()),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("photo", models.ImageField(max_length=50, upload_to="")),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "social_media_link",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[
                            actnow.profiles.validators.validate_social_media_link
                        ],
                    ),
                ),
                ("persons", models.ManyToManyField(to="profiles.UserProfile")),
            ],
        ),
    ]
