# Generated by Django 3.2.3 on 2021-06-15 09:59

import phonenumber_field.modelfields
from django.db import migrations, models

import actnow.profiles.validators


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_organisationprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationprofile",
            name="description",
            field=models.TextField(
                blank=True, max_length=255, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="", verbose_name="photo"),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="social_media_link",
            field=models.URLField(
                blank=True,
                validators=[actnow.profiles.validators.validate_social_media_link],
            ),
        ),
        migrations.AlterField(
            model_name="organisationprofile",
            name="website",
            field=models.URLField(unique=True, verbose_name="website"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=255, verbose_name="about me"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.TextField(blank=True, max_length=255, verbose_name="location"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="", verbose_name="photo"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="social_media_link",
            field=models.URLField(
                blank=True,
                validators=[actnow.profiles.validators.validate_social_media_link],
            ),
        ),
    ]
