# Generated by Django 3.2.3 on 2021-06-15 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_profile_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisationprofile",
            options={"get_latest_by": "updated_at"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"get_latest_by": "updated_at"},
        ),
        migrations.AddField(
            model_name="organisationprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisationprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
