# Generated by Django 3.2.3 on 2021-07-01 12:51

import phonenumber_field.modelfields
from django.db import migrations, models

import actnow.profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_organisationprofile_persons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="about me"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="location"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="photo"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="social_media_link",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[actnow.profiles.validators.validate_social_media_link],
            ),
        ),
    ]
