# Generated by Django 3.2.3 on 2021-07-09 10:33

import phonenumber_field.modelfields
from django.db import migrations, models

import actnow.profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_auto_20210701_1251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True, default="", max_length=255, verbose_name="about me"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="last name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.TextField(
                blank=True, default="", max_length=255, verbose_name="location"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=128,
                region=None,
                verbose_name="phone number",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                blank=True, default="", upload_to="", verbose_name="photo"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="social_media_link",
            field=models.URLField(
                blank=True,
                default="",
                validators=[actnow.profiles.validators.validate_social_media_link],
            ),
            preserve_default=False,
        ),
    ]
