# Generated by Django 3.2.5 on 2021-08-02 15:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_model_blank_charfields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisationprofile",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.RenameField(
            model_name="organisationprofile",
            old_name="persons",
            new_name="owners",
        ),
        migrations.RemoveField(
            model_name="organisationprofile",
            name="description",
        ),
        migrations.AddField(
            model_name="organisationprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=255, verbose_name="about me"),
        ),
        migrations.AddField(
            model_name="organisationprofile",
            name="location",
            field=models.TextField(blank=True, max_length=255, verbose_name="location"),
        ),
        migrations.AddField(
            model_name="organisationprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="name"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, verbose_name="website"),
        ),
    ]
