# Generated by Django 3.2.5 on 2021-08-06 14:34

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_rename_about_me"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organisation_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="profiles.organisationprofile",
                    ),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="profiles.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                check=django.db.models.expressions.RawSQL(
                    "num_nonnulls(organisation_profile_id::bigint , user_profile_id::bigint) = 1",
                    output_field=models.BooleanField(),
                    params=(),
                ),
                name="single_unique_profile",
            ),
        ),
    ]
