name: Dokku CD
on:
  push:
    branches: [ main ]
env:
  DOKKU_APP_NAME: 'actnow'
  DOKKU_HOST: 'dokku-1.dev.codeforafrica.org'
  DOKKU_REMOTE_BRANCH: 'master'
  GIT_PUSH_FLAGS: '--force'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: codeforafrica/actnow:latest
          target: python-app-ci
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: ${{ env.DOKKU_HOST }}
            app-name: ${{ env.DOKKU_APP_NAME }}
            remote-branch: ${{ env.DOKKU_REMOTE_BRANCH }}
            git-push-flags: ${{ env.GIT_PUSH_FLAGS }}
